### ISSUE TITLE
Docker hub images do not exist

### ISSUE THREAD

**Issue by nielsole** [outcoldman/docker-stats-splunk#2]
Hi,

thanks for your effort! I tried following the installation steps and found that the links to dockerhub are broken.

Kind regards

Niels-Ole Kühl

**Comment by yakhyadabo** [comment]
The Splunk team has build their own images : 
- **splunk/splunk:latest** for the entreprise and deployment server
- **splunk/universalforwarder:latest** for the forwarder

The git repo is available here : https://github.com/splunk/docker-splunk

**Comment by nielsole** [comment]
Thank you!
